path:
  raw_path: "./data/raw/"
  processed_path: "./data/processed/"
  artifacts_path: "./artifacts/files/"
  train_results: "./artifacts/outputs/train_results/"
  test_result: "./artifacts/outputs/test_result/"
  train_models: "./artifacts/checkpoints/train_models/"
  test_model: "./artifacts/checkpoints/test_model/"
  metrics_path: "./artifacts/metrics/"

dataloader:
  dataset: "./data/raw/dataset.zip"
  batch_size: 32
  image_size: 32
  split_size: 0.30

netG:
  latent_space: 100
  constant: 128

trainer:
  epochs: 4
  lr: 2e-4
  momentum: 0.75
  beta1: 0.5
  beta2: 0.999
  regularizer: 0.01
  device: "cpu"
  adam: True
  SGD: False
  l1_regularization: False
  l2_regularization: False
  elasticnet_regularization: False
  mlflow: False
  verbose: True

tester:
  quantity: 64
  model: "best"
