path:
  raw_path: "./data/raw/"                                 # Directory for raw data
  processed_path: "./data/processed/"                     # Directory for processed data
  artifacts_path: "./artifacts/files/"                    # Directory for storing artifact files
  train_results: "./artifacts/outputs/train_results/"     # Directory for training outputs
  test_result: "./artifacts/outputs/test_result/"         # Directory for test outputs
  train_models: "./artifacts/checkpoints/train_models/"   # Directory for saved training models
  test_model: "./artifacts/checkpoints/test_model/"       # Directory for the model used in testing
  metrics_path: "./artifacts/metrics/"                    # Directory for saving metrics

dataloader:
  dataset: "./data/raw/dataset.zip"                       # Path to the dataset file
  batch_size: 32                                          # Number of samples per batch
  image_size: 32                                          # Size of input images
  split_size: 0.30                                        # Fraction of data used for validation/testing

netG:
  latent_space: 100                                       # Dimensionality of latent space
  constant: 128                                           # A constant value for the network

trainer:
  epochs: 4                                               # Number of training epochs
  lr: 2e-4                                                # Learning rate
  momentum: 0.75                                          # Momentum value for optimizer
  beta1: 0.5                                              # Beta1 value for Adam optimizer
  beta2: 0.999                                            # Beta2 value for Adam optimizer
  regularizer: 0.01                                       # Regularization strength
  device: "cpu"                                           # Device to use for computation (e.g., cpu or gpu)
  adam: True                                              # Use Adam optimizer if True
  SGD: False                                              # Use SGD optimizer if True
  l1_regularization: False                                # Apply L1 regularization if True
  l2_regularization: False                                # Apply L2 regularization if True
  elasticnet_regularization: False                        # Apply ElasticNet regularization if True
  mlflow: False                                           # Enable MLflow logging if True
  verbose: True                                           # Enable verbose output if True

tester:
  quantity: 64                                            # Number of test samples
  model: "best"                                           # Specify the best model checkpoint for testing
